all:
	g++ ./ave_Accept/ave_accept.cpp -o ./ave_Accept/ave_accept.exe -O2
	g++ ./comp_DoNS/comp_DoNS.cpp -o ./comp_DoNS/comp_DoNS.exe -O2
	g++ ./CSV_all/csv_all.cpp -o ./CSV_all/csv_all.exe -O2

clean:
	rm -f ./ave_Accept/ave_accept.exe
	rm -f ./comp_DoNS/comp_DoNS.exe
	rm -f ./CSV_all/csv_all.exe
	rm -f ./ave_Accept/*.csv
	rm -f ./comp_DoNS/*.csv
	rm -f ./CSV_all/*.csv
	rm -f ./photo/*.png